## AUTO-GENERATED BY GodotGAS PLUGIN. DO NOT EDIT MANUALLY.
##
## Used for accessing StringName references to Gameplay Tags in Scripts.
##
## @meta_addon: GodotGAS 1.0
## @meta_author: YulRun (https://YulRun.Dev)
## @meta_license: MIT

@tool
class_name GameplayTags

const Example_Event_Damage_Critical: StringName = &"Example.Event.Damage.Critical"
const Example_Event_Damage_Missed: StringName = &"Example.Event.Damage.Missed"
const Example_Event_Damage_Normal: StringName = &"Example.Event.Damage.Normal"
